/:
    pattern:  /
    defaults: { _controller: HoaxCoreBundle:Default:index }

ingredients:
    pattern:  /ingredients
    defaults: { _controller: HoaxCoreBundle:Ingredient:index }

recipes:
    pattern:  /recipes
    defaults: { _controller: HoaxCoreBundle:Recipe:index }
